version: "3.1"

services:
  zookeeper:
    container_name: zookeeper
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    volumes:
      - zookeeper_data:/bitnami/zookeeper
    networks:
      - kafka-cluster
  kafka-0:
    container_name: kafka-0
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_BROKER_ID: 0
      ALLOW_PLAINTEXT_LISTENER: yes
    volumes:
      - kafka_0_data:/bitnami/kafka
    depends_on:
      - zookeeper
    networks:
      - kafka-cluster
  kafka-1:
    container_name: kafka-1
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "9093:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_BROKER_ID: 1
      ALLOW_PLAINTEXT_LISTENER: yes
    volumes:
      - kafka_1_data:/bitnami/kafka
    depends_on:
      - zookeeper
    networks:
      - kafka-cluster
  kafka-2:
    container_name: kafka-2
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "9094:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_BROKER_ID: 2
      ALLOW_PLAINTEXT_LISTENER: yes
    volumes:
      - kafka_2_data:/bitnami/kafka
    depends_on:
      - zookeeper
    networks:
      - kafka-cluster

volumes:
  zookeeper_data:
    driver: local
  kafka_0_data:
    driver: local
  kafka_1_data:
    driver: local
  kafka_2_data:
    driver: local
networks:
  kafka-cluster:
    driver: bridge
