---
apiVersion: v1
kind: Namespace
metadata:
  name: mflyyou-dev
---
apiVersion: v1
kind: Pod
metadata:
  name: config-properties
  namespace: mflyyou-dev
spec:
  containers:
    - name: config-properties
      image: ghcr.io/zhangpanqin/config-properties:b382c15
      imagePullPolicy: IfNotPresent
      ports:
        - name: application
          containerPort: 8080
          protocol: TCP
        - name: actuator
          containerPort: 9090
          protocol: TCP
      #      readinessProbe:
      #        httpGet:
      #          port: 9090
      #          path: /actuator/health/readiness
      #        initialDelaySeconds: 10
      #      livenessProbe:
      #        httpGet:
      #          port: 9090
      #          path: /actuator/health/liveness
      #        initialDelaySeconds: 10
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 200m
          memory: 128Mi